### PR TITLE
Optional proxy usage toggle

### PR DESCRIPTION
**Pull request by kostyrevaa**
This PR adds ability to install repo-file through proxy server

### CODE REVIEW

**Comment by geerlingguy** [comment]
I'll leave this open a bit, but I wanted to mention that I usually recommend proxies be configured system-wide prior to running roles like this one.

**Comment by kostyrevaa** [comment]
I am not following you
I did configure proxy in /etc/environment
but without the change this PR introduces get_url defaults to use_proxy: no

**Comment by kostyrevaa** [comment]
Oh
I was wrong
get_url defaults to use_proxy: yes
I'm closing it then
sorry for buzz

**Comment by geerlingguy** [comment]
No problem!

**Pull request closed without merging**
