### PR TITLE
Fix role vars based on jenkins_prefer_lts

### PR DESCRIPTION
**Pull request by ashokm**

### CODE REVIEW

**Comment by nhojpatrick** [comment]
This patch works for me if you only want to use a specific LTS version, i.e.

```
jenkins_prefer_lts: true
jenkins_version: "2.204.6"
```

**Comment by tobias-richter** [comment]
+1

**Comment by nhojpatrick** [comment]
@geerlingguy any chance to review

**Comment by nhojpatrick** [comment]
is not stale just waiting for @geerlingguy to merge

**Pull request closed without merging**
