### PR TITLE
Fixes GPG error when using spacewalk/satellite and adds option to use proxy to install plugins

### PR DESCRIPTION
**Pull request by rvsantoro**
Hello

When I was using your Jenkins role to install Jenkins I got an error when it was trying to add a GPG key even though I specified `jenkins_repo_url = ''`.  I found a quick fix for this by using the same logic you did to not add the repo.  I then ran into an issue with installing Jenkins plugins because I am behind a corporate proxy.  The solution I provided works without any issues for me and I hope you like it as well.

### CODE REVIEW

**Comment by rvsantoro** [comment]
I was going by ansible's documentation when using yes or no, would you like me  to change these to true and false?

**Comment by rvsantoro** [comment]
This is awesome thank you @bbaassssiiee

**Comment by rvsantoro** [comment]
@bbaassssiiee I was fixing a merge conflict because a new variable was added to defaults/main.yml and it looks like the Ubuntu 18.04 check failed because of a hiccup with pypi.  Is there a way to restart the build check just for that OS?

**Comment by bbaassssiiee** [comment]
@geerlingguy needs to restart it.

**Pull request closed without merging**
