### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by adborden**
Fix typo, `false` (weekly builds) are the default. Set `jenkins_prefer_lts: true` to use the current LTS version.

### CODE REVIEW

**Comment by adborden** [comment]
Hello, I'm still interested in getting this minor PR merged. Let me know if any changes are necessary.

**Comment by adborden** [comment]
Hello, I'm still interested in getting this minor PR merged. Let me know if any changes are necessary.

**Comment by m8ram** [comment]
This fixes issue  #336.

**Comment by adborden** [comment]
Hello, I'm still interested in getting this minor PR merged. Let me know if any changes are necessary.

**Pull request closed without merging**
