### PR TITLE
Allow https request and work behind a  reverse proxy

### LINKED ISSUE #111: Installation doesn't work when hostname is accessible via https only
```
shell: "curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/"
```
This assumes http is always available. Since the playbook runs on the target server, I suggest changing `http://{{ jenkins_hostname }}` to `http://localhost` or provide an option to configure the protocol.

### PR DESCRIPTION
**Pull request by thiagogomesverissimo**
In this role, the `jenkins_http_port` variable is used in jenkins configuration and to do some curl requests. 
In the scenario that jenkins is behind a reverse proxy, this ports can be different. 
So I created `jenkins_reverse_proxy_port`, that by default is equal to `jenkins_http_port`, but can be easily changed in playbook. 

The http was hard coded in the curl requests, so a I created `jenkins_protocol` variable to attend who use https.

Fix #111

### CODE REVIEW

**Comment by thiagogomesverissimo** [comment]
Travis is failing before this PR (https://travis-ci.org/geerlingguy/ansible-role-jenkins/builds/405156823), right?

**Comment by thiagogomesverissimo** [comment]
I will rebase.

**Comment by davelosert** [comment]
Any update on this PR? 
Would be great if it could be merged soon as I have the same issue right now.

Is there anything I can do to help?

**Comment by geerlingguy** [comment]
This seems a bit confusing to me—it looks like this is just replacing `jenkins_http_port` with the new variable?

I am currently using Jenkins behind Nginx as a reverse proxy without issue for a great number of Jenkins servers, and Nginx is successfully serving it as HTTPS while Jenkins is accessible over whatever port it needs to be on the server itself, via http.

I'm trying to see what the use case would be here and why it needs a different variable name?

**Comment by thiagogomesverissimo** [comment]
Firstly,  
@geerlingguy thank you! I have learned a lot from yours roles and your book.

The scenario is Jenkins with port 8080 and http (basically the default) behind Nginx as a reverse proxy, but delivering jenkins in port 443 with https.

**Comment by davelosert** [comment]
@geerlingguy : In my case, I have a setup on AWS.
My Jenkins is running on an EC2 Instance, listening on Port 8080, in a private network.
Web-Access is controlled by a Loadbalancer listening on Port 443 - lets say to the domina "jenkins.test.com" and forwarding requests to the EC2 on Port 8080. Port 80 is only redirecting to https.

So the problem is:
If Jenkins now tries to access itself with it "http://jenkins.test.com", it will receive a status 301.
The test in your role however only succeeds if it receives a status 200 - thus it retries infinitly.

**Pull request closed without merging**
