### PR TITLE
jenkins_prefer_lts fix for failed downloading

### PR DESCRIPTION
**Pull request by nhojpatrick**
tweak package url for lts installations.

### CODE REVIEW

**Comment by nhojpatrick** [comment]
Covers same issue as previously raised in earlier PR https://github.com/geerlingguy/ansible-role-jenkins/pull/343

**Comment by brootware** [comment]
Seems like this is a duplicate of https://github.com/geerlingguy/ansible-role-jenkins/pull/343.

**Comment by nhojpatrick** [comment]
> Thank you for this fix @nhojpatrick. But seems like this is a duplicate of #343. You can close this PR since it's the same.

@brootware #343 only fixes/solves Debian, this PR also fixes/solves RedHat.

@geerlingguy it's good your develop so many modules, but it is also annoying if people start using them and they are not supported. If you don't plan on supporting them maybe keep them private...

**Comment by geerlingguy** [comment]
@nhojpatrick - Please see https://www.jeffgeerling.com/blog/2022/burden-open-source-maintainer

I support these for my own use cases, and can guarantee they will work for the things I use them for.

I sometimes merge features that expand the functionality for others if I see value in them, but those secondary features are nice-to-have, and if your business relies on any of the functionality in these roles, I would advise forking the role, using your copy, and merging upstream changes from mine if you desire ;)

**Pull request closed without merging**
