### PR TITLE
Using Ansible jenkins_plugin module to install plugins.

### LINKED ISSUE #106: Install Jenkins plugins using password failed
TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] ***********
failed: [ec2-52-213-150-14.eu-west-1.compute.amazonaws.com] (item=git-parameter) => {"changed": true, "cmd": ["java", "-jar", "/opt/jenkins-cli.jar", "-s", "http://localhost:8080/", "install-plugin", "git-parameter", "--username", "admin", "--password", "admin"], "delta": "0:00:07.937499", "end": "2016-12-25 18:32:26.503943", "failed": true, "item": "git-parameter", "rc": 255, "start": "2016-12-25 18:32:18.566444", "stderr": "Dec 25, 2016 6:32:26 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run\nSEVERE: I/O error in channel Chunked connection to http://localhost:8080/cli\njava.io.IOException: Unexpected termination of the channel\n\tat hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:73)\nCaused by: java.io.EOFException\n\tat java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2353)\n\tat java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2822)\n\tat java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)\n\tat java.io.ObjectInputStream.<init>(ObjectInputStream.java:301)\n\tat hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)\n\tat hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)\n\tat hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)\n\nhudson.remoting.RequestAbortedException: java.io.IOException: Unexpected termination of the channel\n\tat hudson.remoting.Request.abort(Request.java:307)\n\tat hudson.remoting.Channel.terminate(Channel.java:888)\n\tat hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:92)\n\tat ......remote call to Chunked connection to http://localhost:8080/cli(Native Method)\n\tat hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1537)\n\tat hudson.remoting.Request.call(Request.java:172)\n\tat hudson.remoting.Channel.call(Channel.java:821)\n\tat hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:256)\n\tat com.sun.proxy.$Proxy3.main(Unknown Source)\n\tat hudson.cli.CLI.execute(CLI.java:333)\n\tat hudson.cli.CLI._main(CLI.java:504)\n\tat hudson.cli.CLI.main(CLI.java:385)\nCaused by: java.io.IOException: Unexpected termination of the channel\n\tat hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:73)\nCaused by: java.io.EOFException\n\tat java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2353)\n\tat java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2822)\n\tat java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)\n\tat java.io.ObjectInputStream.<init>(ObjectInputStream.java:301)\n\tat hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)\n\tat hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)\n\tat hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)", "stdout": "Installing git-parameter from update center", "stdout_lines": ["Installing git-parameter from update center"], "warnings": []}

### PR DESCRIPTION
**Pull request by dizeee**
Fixes #106.
Breaks BC with Ansible < 2.2.

### CODE REVIEW

**Comment by dizeee** [comment]
I guess I need to update tests to cover the new code. I'll have time for that either later today or tomorrow.

**Comment by dizeee** [comment]
@geerlingguy It looks like python in your Ubuntu 14.04 lacks SNI support. It was OK with curl that has it built in, but now communicating with https://updates.jenkins-ci.org/ is done by Ansible and it fails to verify the SSL certificate. Python >= 2.7.9 supports SNI.

**Comment by dizeee** [comment]
That's it so far. I tried to add more configurable options but they don't seem to work in a loop. Unfortunately I don't have much time right now to investigate. Please take a look at this commit https://github.com/ozean12/ansible-role-jenkins/commit/d317aef4cbf7173c0b224b3d8c38113e338f02ab, maybe you'll be able to figure it out. Anyway this PR fully reflects previous behavior with less code and in a more straight forward and stable way.

**Comment by leifmadsen** [comment]
@dizeee I'd like to add to this functionality in another commit where it adds ability to pin plugins to a version. Thanks for submitting this!

**Comment by dizeee** [comment]
@leifmadsen Did you manage to make it work in a loop? In this commit https://github.com/ozean12/ansible-role-jenkins/commit/d317aef4cbf7173c0b224b3d8c38113e338f02ab I tried to add more configurable options including version pinning, but somehow it doesn't work in a loop for me.

**Comment by leifmadsen** [comment]
@dizeee I haven't actually had a chance to try this patch at all yet. I just found it about 20 mins ago while thinking about some work I was planning to do today. Thought I better check if someone had started on this work :)

More to report later today hopefully!

**Comment by dizeee** [comment]
@leifmadsen Also Ansible doesn't resolve dependencies for packages with pinned versions and it works slower. So I just gave up on this, as I don't need it anyway. Maybe you'll have better luck. We just need @geerlingguy to update Python on his test nodes and merge this PR ;)

**Comment by leifmadsen** [comment]
@dizeee well I'll give it the ol' college try :)

**Comment by manjitkumar** [comment]
It's failing for me if python verison is below 2.7.9 i.e 2.7.6 on ubuntu 14.04.
```json
failed: [10.254.254.98] (item=github) => {
    "failed": true,
    "invocation": {
        "module_args": {
            "backup": null,
            "content": null,
            "delimiter": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": true,
            "group": "jenkins",
            "http_agent": "ansible-httpget",
            "jenkins_home": "/var/lib/jenkins",
            "mode": "0644",
            "name": "github",
            "owner": "jenkins",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "present",
            "timeout": 30.0,
            "unsafe_writes": null,
            "updates_expiration": 86400,
            "updates_url": "https://updates.jenkins-ci.org",
            "url": "http://internal-ci.sample.io:8080",
            "url_password": "admin",
            "url_username": "admin",
            "use_proxy": true,
            "validate_certs": true,
            "version": null,
            "with_dependencies": true
        },
        "module_name": "jenkins_plugin"
    },
    "item": "github",
    "msg": "Failed to validate the SSL certificate for updates.jenkins-ci.org:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"
}```

**Comment by dizeee** [comment]
@manjitkumar Yes it does, as I already pointed out in this thread. Jenkins uses SNI to serve it's https sites and Python supports SNI since 2.7.9.

**Comment by geerlingguy** [comment]
Testing this now in a separate branch. I've been working with the `jenkins_` modules this week and would like to start moving my role to using them since they make life a lot easier.

**Pull request closed without merging**
