### PR TITLE
Added jenkins_updates_url variable

### PR DESCRIPTION
**Pull request by krumstein**
Added this variable and set it to "https://updates.jenkins.io" since, the default one in outdated.

### CODE REVIEW

**Comment by CloudSurgeon** [comment]
Was just about to do something here, after running into the issue this morning. Thanks!

**Comment by CloudSurgeon** [comment]
LGTM. Tested and works in my environment, as well as molecule.

**Comment by CloudSurgeon** [comment]
Looks like this dupes #231 and #237

**Comment by krumstein** [comment]
Thanks for your reply!
Not really, these PR add updates URL to update task. My PR changes plugin
installation task. Since today the TLS has expired for
https://updates.jenkins-ci.org the task for installation fails. My PR fixes
it :) I will shortly update the description to make it more clear.

Best wishes,
Vladimir Krumshtein.

сб, 9 февр. 2019 г., 20:47 Adam Bowen notifications@github.com:

**Comment by geerlingguy** [comment]
I'm hitting this on a ton of my builds too. TIL that the URL I was using is deprecated...

https://twitter.com/agentdero/status/1095060183359737856

**Pull request merged**
