### PR TITLE
Fixed bug

### PR DESCRIPTION
**Pull request by mdsouza19**
Fixed bug which gives this error:

fatal: [10.3.34.26]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: path"}

### CODE REVIEW

**Comment by seenickcode** [comment]
@geerlingguy note this is a key fix for me as I just tried `ansible-role-jenkins` with a fresh playbook and was hitting a wall until I incorporated this change.

**Comment by maxim-nazarenko** [comment]
First of all, @geerlingguy  thank you for your roles - they are awesome! 
@mdsouza19 thank you for the PR.

What is the current status of this PR?
@mdsouza19, maybe you can pull the changes from the upstream to prevent merge conflict?

**Comment by mdsouza19** [comment]
Pulled changes from master...

**Comment by mdsouza19** [comment]
@maxim-nazarenko @seenickcode I resubmitted a PR:
https://github.com/geerlingguy/ansible-role-jenkins/pull/201

**Comment by maxim-nazarenko** [comment]
@mdsouza19 thank you!
waiting for @geerlingguy to merge #201

**Pull request closed without merging**
