### PR TITLE
enable jenkins_use_lts flag

### PR DESCRIPTION
**Pull request by ludicruz**
backwards compatibility preserved by default to false

### CODE REVIEW

**Comment by geerlingguy** [comment]
I think I'd like to do this a little differently, where we just use a repo/key variable defined in `defaults/vars.yml`, and then your playbook can override if need be. I'd like to default to the latest still (to not break anyone's existing expectations. And if you want to use LTS, set the vars in your playbook's vars.

This option should definitely be documented in the README. If you don't have time to rework the PR, I'll work on it separately at some point.

**Comment by ludicruz** [comment]
like so?

**Comment by geerlingguy** [comment]
Very close, and thanks for keeping with this :)

Instead of having a bunch of distro-specific variables to expose to the end user, I'd like to use just:

  - `jenkins_repo_url`
  - `jenkins_repo_key_url`

Then we provide default variables inside `vars/Debian.yml` and `vars/RedHat.yml` like:

```
__jenkins_repo_url: default-url-here
__jenkins_repo_key_url: default-url-here
```

And inside the main task yml file, we can set the defaults if the actual variable (not prefixed with `__`) is already provided, e.g. by the calling playbook or in an inventory file.

See, for an example:

  - https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/main.yml#L3
  - https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/main.yml#L11
  - https://github.com/geerlingguy/ansible-role-php/blob/master/vars/Debian.yml

Does that give enough to go on? If you can get close, I'll merge then clean things up if they need any more tweaking. Thanks for your help!

**Comment by ludicruz** [comment]
like so?

**Comment by geerlingguy** [comment]
Perfect!

**Pull request merged**
