### PR TITLE
Switch from using curl command to CLI module to check startup success

### PR DESCRIPTION
**Pull request by andreasscherbaum**

### CODE REVIEW

**Comment by mkesper** [comment]
Better to fix the use of curl (what the warning says), no?

**Comment by andreasscherbaum** [comment]
Well, turns out with a number tricks (not sure what works with older Ansible versions) it is possible to change this to "uri" instead of "shell".

**Comment by geerlingguy** [comment]
I approve this PR; don't want to merge in a bugfix release though; will merge for next minor or major release.

**Comment by andreasscherbaum** [comment]
Are you still planning to merge this PR?

**Comment by andreasscherbaum** [comment]
@geerlingguy I've updated the PR, and rebased it against master.

Seems like the CI is passing the tests, but then failing because the "lint" step has problems.

**Comment by mkesper** [comment]
@geerlingguy The lint checks for strict YAML syntax but ansible doesn't really use that (sadly).
See for example https://github.com/ansible/ansible/issues/11905
Lint contradicts the [ansible documentation](https://docs.ansible.com/ansible/latest/modules/uri_module.html) here

**Comment by andreasscherbaum** [comment]
If I read that correctly, it should be:
```
return_content: 'yes'
follow_redirects: 'no'
```

to make the lint check happy? Correct?

**Comment by andreasscherbaum** [comment]
Any chance this can be merged? This PR is open for a long time ... Thanks!

**Comment by andreasscherbaum** [comment]
@geerlingguy What is missing from this PR to get it merged? Thanks.

**Comment by andreasscherbaum** [comment]
I took a look at the failing yamllint checks, and got it working. All tests are green now.

**Comment by andreasscherbaum** [comment]
*alive*

**Comment by geerlingguy** [comment]
_merged_

Heh, sorry about missing this one, I'm trying to make sure to sweep through some of the simpler improvements in PRs now.

**Comment by andreasscherbaum** [comment]
Thanks for merging it.

**Pull request merged**
