### PR TITLE
Plugin Database Update

### PR DESCRIPTION
**Pull request by robbinscp**
* Update plugin database before installing Jenkins plugins (eliminates build failures).  See the following for additional information - 
- http://www.mymiller.name/wordpress/app/1515/
- https://www.jeffgeerling.com/blog/2017/ansible-jenkinsplugin-module-and-404-plugin-not-found

### CODE REVIEW

**Comment by geerlingguy** [comment]
Haha, I can't believe I kept getting hit by my own bug. Thanks @robbinscp !

**Comment by timblaktu** [comment]
Hmm, @geerlingguy @robbinscp I'm getting 404s during plugin install and using version 4.3.0 of this role. Did this fix go away or change in the last 2.5 years?

I found this variable which seems to default to a long time between updating plugin cache:

jenkins_plugin_updates_expiration: 86400

I set it to zero and am still getting 404 errors. I know this will go away if I wait a day or two, but I'd like to get a persistent solution to it. Can you suggest how I can configure this this role to prevent 404s? I am not concerned with it taking longer to run.

Thanks.

**Comment by geerlingguy** [comment]
@timblaktu - I run a CI job that tests this role daily, and that job fails due to random 404s and 50x errors quite frequently. Unfortunately, the Jenkins plugin mirrors are historically unreliable. For a time, I was also building a Jenkins docker image that would install a couple plugins on a CI job, and that, too, would fail here and there for hours at a time. Then, mysteriously, it would work the next day... or three days later. Then it would break again in a week or two. Then work again.

That's kind of the status quo for Jenkins plugin installs, unfortunately.

**Comment by timblaktu** [comment]
Thanks @geerlingguy, I will check again in a few days and hope it starts working.

Now I just gotta figure out why none of my plugin dependencies are being installed.. I'll raise another issue. I know there's been several related issues on this, but now I'm seeing this problem even with `jenkins_plugins_install_dependencies: true` and `jenkins_plugins_state: present` and no plugin versions specified. Not sure why the dependencies aren't being installed. It's nothing to do with the 404 failure, bc I've commented our the failing plugin, and have done a complete re-provision from fresh OS install bootstrap then run my jenkins.yml playbook which includes your role..

**Comment by timblaktu** [comment]
@geerlingguy, what about 17 days? locks-and-latches plugin is still giving me 404 errors. I'm going to have to stop using this method (ansible jenkins_plugin module) for plugin installation if it's this unreliable. [It would seem](https://www.jenkins.io/doc/book/managing/plugins/#advanced-installation) that all that's required is to place each plugin's .hpi file into JENKINS_HOME/plugins and restart. Perhaps I could just create my own jenkins plugin mirror, or just create a local cache of these hpi files that I need? Do you know of or have you experimented with alternatives?

**Pull request merged**
